### ISSUE TITLE
Range slider clashes with webcomponents.js

### ISSUE THREAD

**Issue by rjsteinert** [rovervannispen/algolia-element#4]
Hi there. This is not really a issue with your element but I'm wondering if you have run into this issue as you have stated that you plan to support the instantsearch range sliders. If you haven't run into this yet, then head up! :-) 

https://github.com/algolia/instantsearch.js/issues/3099

**Comment by rovervannispen** [comment]
Hi @rjsteinert, I stopped working on this element because of too little time at the moment...
